# SITE CONFIGURATION
baseurl: "/blobot.netflix"
url: "https://textelz.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Netflix on Blobot                                # site's title
description: "넷플릭스 콘텐츠 해외 리뷰 & 평점 가이드"           # used by search engines
avatar: assets/img/textelz.png                          # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: 넷플릭스 콘텐츠 해외 리뷰 & 평점 가이드             # Change Blog header text
header_feature_image: assets/img/header/triangular.jpeg
header_feature_image_responsive: true
footer_text: >
  Powered by Textelz

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for comments, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics: G-5HLVDH8FHH                          # Measurement ID, e.g. "G-00000"
cookie_consent: true                                    # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# PAGINATION
paginate: 10
paginate_path: "/blog/page:num"
future: true

# POSTS
# collections:
  # posts_2016:
  #   output: true
  #   permalink: /:collection/:name

# _posts 하위 폴더도 인식하도록 설정
include:
  - _posts/posts_2010


# BUILD SETTINGS
sass:
  style: compressed
  quiet_deps: true
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-sitemap]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*", ".github/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
